"""
config.py — Central configuration for the Lead Scoring backend.
Update MODEL_PATH, SCALER_PATH, and FEATURE_NAMES_PATH once your
notebooks have generated the ML artifacts.
"""

import os
from pathlib import Path

# ── Directory Layout ───────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent          # repo root
DATA_DIR = BASE_DIR / "data" / "processed"
MODELS_DIR = BASE_DIR / "models"
OUTPUTS_DIR = BASE_DIR / "outputs"

# Ensure outputs directory exists
OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)

# ── ML Artifact Paths ──────────────────────────────────────────────────────────
# All three artifacts are saved in models/ by the notebooks
MODEL_PATH = MODELS_DIR / "best_baseline_model.pkl"    # generated by 03_baseline_models
SCALER_PATH = MODELS_DIR / "scaler.pkl"                # generated by 02_preprocessing
FEATURE_NAMES_PATH = MODELS_DIR / "feature_names.json" # generated by 02_preprocessing

# ── Scoring Thresholds (probability → tier) ────────────────────────────────────
TIER_THRESHOLDS = {
    "Hot":    0.80,   # probability >= 0.80  → Hot
    "Warm":   0.50,   # probability >= 0.50  → Warm
    "Cold":   0.20,   # probability >= 0.20  → Cold
    # below 0.20 → Frozen
}

# ── Business Rule: VIP Companies ───────────────────────────────────────────────
# Leads from these companies are always scored 90+
VIP_COMPANIES: list[str] = [
    "Google",
    "Microsoft",
    "Amazon",
    "Apple",
    "Meta",
]

# ── Business Rule: Target Countries ────────────────────────────────────────────
# Leads outside this list are capped at 40 if their model score < 60
TARGET_COUNTRIES: list[str] = [
    "India",
    "United States",
    "United Kingdom",
    "Canada",
    "Australia",
    "Germany",
    "Singapore",
]

# ── Business Rule: Disposable / Spam Email Domains ────────────────────────────
SPAM_DOMAINS: list[str] = [
    "mailinator.com",
    "guerrillamail.com",
    "throwaway.email",
    "tempmail.com",
    "10minutemail.com",
    "trashmail.com",
    "yopmail.com",
]

# ── App Metadata ───────────────────────────────────────────────────────────────
APP_TITLE = "X Education Lead Scoring API"
APP_DESCRIPTION = (
    "Predict lead conversion probability and assign actionable tiers "
    "(Hot / Warm / Cold / Frozen) to help sales teams prioritise outreach."
)
APP_VERSION = "1.0.0"
MODEL_VERSION = "1.0.0"
MODEL_TYPE = "XGBoost"                  # update if you switch algorithms
TRAINING_DATE = "2024-01-15"            # update after retraining
REPORTED_TEST_AUC = 0.87               # update with real AUC from Phase 4

# ── Server ─────────────────────────────────────────────────────────────────────
HOST = os.getenv("HOST", "0.0.0.0")
PORT = int(os.getenv("PORT", 8000))
RELOAD = os.getenv("RELOAD", "true").lower() == "true"
